config/routes.rb
Gmaps::Application.routes.draw do
  resources :ip_addresses

  resources :locations
  root :to => "locations#index"

end

app/models/ip_address.rb
class IpAddress < ActiveRecord::Base
  attr_accessible :latitude, :location, :longitude

  geocoded_by :location,
              :latitude => :latitude, :longitude => :longitude
  after_validation :geocode
end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :address, :latitude, :longitude

  geocoded_by :address
  after_validation :geocode, :if => :address_changed?
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/ip_addresses_controller.rb
class IpAddressesController < ApplicationController
  # GET /ip_addresses
  # GET /ip_addresses.json
  def index
    @ip_addresses = IpAddress.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ip_addresses }
    end
  end

  # GET /ip_addresses/1
  # GET /ip_addresses/1.json
  def show
    @ip_address = IpAddress.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ip_address }
    end
  end

  # GET /ip_addresses/new
  # GET /ip_addresses/new.json
  def new
    @ip_address = IpAddress.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ip_address }
    end
  end

  # GET /ip_addresses/1/edit
  def edit
    @ip_address = IpAddress.find(params[:id])
  end

  # POST /ip_addresses
  # POST /ip_addresses.json
  def create
    @ip_address = IpAddress.new(params[:ip_address])

    respond_to do |format|
      if @ip_address.save
        format.html { redirect_to @ip_address, notice: 'Ip address was successfully created.' }
        format.json { render json: @ip_address, status: :created, location: @ip_address }
      else
        format.html { render action: "new" }
        format.json { render json: @ip_address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ip_addresses/1
  # PUT /ip_addresses/1.json
  def update
    @ip_address = IpAddress.find(params[:id])

    respond_to do |format|
      if @ip_address.update_attributes(params[:ip_address])
        format.html { redirect_to @ip_address, notice: 'Ip address was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @ip_address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ip_addresses/1
  # DELETE /ip_addresses/1.json
  def destroy
    @ip_address = IpAddress.find(params[:id])
    @ip_address.destroy

    respond_to do |format|
      format.html { redirect_to ip_addresses_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  # GET /locations
  # GET /locations.json
  def index
    if params[:search].present?
      @locations = Location.near(params[:search], 50, :order => :distance)
    else
      @locations = Location.all
    end
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
    @location = Location.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @location }
    end
  end

  # GET /locations/new
  # GET /locations/new.json
  def new
    @location = Location.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @location }
    end
  end

  # GET /locations/1/edit
  def edit
    @location = Location.find(params[:id])
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.location.new(params[:location])

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render json: @location, status: :created, location: @location }
      else
        format.html { render action: "new" }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /locations/1
  # PUT /locations/1.json
  def update
    @location = Location.find(params[:id])

    respond_to do |format|
      if @location.update_attributes(params[:location])
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location = Location.find(params[:id])
    @location.destroy

    respond_to do |format|
      format.html { redirect_to locations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ip_addresses_helper.rb
module IpAddressesHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/ip_addresses/_form.html.erb
<%= form_for(@ip_address) do |f| %>
  <% if @ip_address.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ip_address.errors.count, "error") %> prohibited this ip_address from being saved:</h2>

      <ul>
      <% @ip_address.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location, :value => request.ip %>
  </div>
    <%= f.submit %>
  </div>
<% end %>

app/views/ip_addresses/edit.html.erb
<h1>Editing ip_address</h1>

<%= render 'form' %>

<%= link_to 'Show', @ip_address %> |
<%= link_to 'Back', ip_addresses_path %>

app/views/ip_addresses/index.html.erb
<h1>Listing ip_addresses</h1>

<table>
  <tr>
    <th>Location</th>
    <th>Latitude</th>
    <th>Longitude</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ip_addresses.each do |ip_address| %>
  <tr>
    <td><%= ip_address.location %></td>
    <td><%= ip_address.latitude %></td>
    <td><%= ip_address.longitude %></td>
    <td><%= link_to 'Show', ip_address %></td>
    <td><%= link_to 'Edit', edit_ip_address_path(ip_address) %></td>
    <td><%= link_to 'Destroy', ip_address, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Ip address', new_ip_address_path %>

app/views/ip_addresses/new.html.erb
<h1>New ip_address</h1>

<%= render 'form' %>

<%= link_to 'Back', ip_addresses_path %>

app/views/ip_addresses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Location:</b>
  <%= @ip_address.location %>
</p>

<p>
  <b>Latitude:</b>
  <%= @ip_address.latitude %>
</p>

<p>
  <b>Longitude:</b>
  <%= @ip_address.longitude %>
</p>


<%= link_to 'Edit', edit_ip_address_path(@ip_address) %> |
<%= link_to 'Back', ip_addresses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gmaps</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBlnjO4sqObdXocPOwv-ZuReE2-Iufn51A&sensor=false"></script>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<h1>Locations</h1>

<%= form_tag locations_path, :method => :get do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search Near", :name => nil %>
<% end %>


<h1>Listing locations</h1>

<table>
  <tr>
    <th>Address</th>
    <th>Latitude</th>
    <th>Longitude</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @locations.each do |location| %>
  <tr>
    <td><%= location.address %></td>
    <td><%= location.latitude %></td>
    <td><%= location.longitude %></td>
    <td><%= link_to 'Show', location %></td>
    <td><%= link_to 'Edit', edit_location_path(location) %></td>
    <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Location', new_location_path %>

app/views/locations/new.html.erb
<h1>New location</h1>

<%= render 'form' %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>
<%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@location.latitude}%2C#{@location.longitude}" %>
<p>
  <b>Address:</b>
  <%= @location.address %>
</p>

<p>
  <b>Latitude:</b>
  <%= @location.latitude %>
</p>

<p>
  <b>Longitude:</b>
  <%= @location.longitude %>
</p>


<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>